### ISSUE TITLE
404 side bar links

### ISSUE THREAD

**Issue by Abrasha** [scala/scala.github.com#826] opened 2017-07-24 09:36 UTC
All of the links from side bar on page are pointing to non-existing URLs.
![collections side bar](https://user-images.githubusercontent.com/11317222/28517274-8b6f1412-706c-11e7-8b87-a71cb2c48338.png)

---

404:
![404 page scala collections](https://user-images.githubusercontent.com/11317222/28517317-aae41504-706c-11e7-97e9-0113c167c096.png)

Link: http://docs.scala-lang.org/overviews/collections/overview.html

**Comment by Abrasha** [comment] 2017-07-24 10:17
For example, the valid link for `Traversable` should be:
http://docs.scala-lang.org/overviews/collections/trait-traversable.html

But actually, it is:
http://docs.scala-lang.org/overviews/collections/trait-traversable

**Comment by heathermiller** [comment] 2017-07-24 10:18
Duplicate of #819 
Thanks for reporting though! It's appreciated 🙂

**Closed by heathermiller** 2017-07-24 10:18 UTC

**Comment by Abrasha** [comment] 2017-07-24 10:20
Oops, my bad. Thank you, @heathermiller

**Comment by heathermiller** [comment] 2017-07-24 10:22
No worries! Not "your bad" at all. Thanks for being proactive and reporting the issue to us!

**Comment by heathermiller** [comment] 2017-07-24 10:24
(Btw, it should be fixed now, thanks to @jrudolph and @jiminhsieh in #824)

**Comment by Abrasha** [comment] 2017-07-24 11:01
@heathermiller you are right. It works now. Great job :)
