### ISSUE TITLE
spammy, insulting comments on front page of site

### ISSUE THREAD

**Issue by SethTisue** [scala/scala.github.com#467] opened 2015-11-12 01:08 UTC
3 of 5 are insults.

<img width="480" alt="screen shot 2015-11-11 at 8 05 44 pm" src="https://cloud.githubusercontent.com/assets/161079/11107884/b58b72be-88af-11e5-957a-893d93b7b0a7.png">

unmoderated comments sections are an open invitation for this kind of thing. if we don't have time to monitor the comments (and I'm pretty sure we don't), perhaps the Disqus stuff should simply be disabled.

wdyt @heathermiller?

**Comment by heathermiller** [comment] 2015-11-12 08:48
It wasn't always so vulgar and useless. It was actually originally a good way to see where discussions were happening or where people were asking questions. Especially on SIPs.

If we remove it, we also have a gaping hole on the front page.

Another idea would be to up the moderation settings in Disqus. I think that profane comments can be set to get caught in a moderation filter. That could at least limit negativity without leaving a gap on the front page.

But I don't feel too strongly about this issue. So if you'd really rather remove the comments, go ahead.

**Comment by soc** [comment] 2015-11-12 09:38
While I think these comments should be removed, I think looking at the other comments shows that many people arrive at a page with very different expectations i. e. Introduction: http://docs.scala-lang.org/tutorials/tour/tour-of-scala.html

> Boah, a introduction shouldn't just throw keywords around, but go from "unknown to known", from "simple to complex". Wonder how many people have been scared away from Scala just from this introduction!

> This document contains a random ordering of topics. I don't like the examples.

> My takeaway from reading this intro is that Scala is some kind of alien technology

> Huh, I'm interested in Scala and have just went through some basic docs/tuts but I must say it is very unclear and - may I even say - simply badly written. 

> It is better to only read titles and then move on to the next chapter.

> The scala community would benefit greatly from a more useful and better written tutorial. I find it easier to learn scala using the Spark primer!

> OMG, yet another article about Scala which says nothing informative at all, but rather throws around some smart looking mathy terminologies. [...] All what I find is articles from one of two ends of the spectrum: 1) piece meal how-to articles with no coherence or flow, which are aimed for programmers (coders), and 2) academic style articles passionately advocating the greatness of some of the funny named constructs

> I am still guessing what it is for,, but i will learn it later

> This is the worst language tutorial I've ever read.

**Comment by soc** [comment] 2015-11-12 09:41
Maybe we should remove the comments and add a link to the bug tracker.

**Comment by densh** [comment] 2015-11-12 09:50
@heathermiller All the constructive discussion has moved to github & gitter & mailing lists. Why not just redirect people there? What's the value of comments that nobody follows?

**Comment by heathermiller** [comment] 2015-11-12 09:58
@soc @densh Please feel free to make PRs addressing the issues you see.

**Comment by soc** [comment] 2015-11-12 10:51
@heathermiller Would it make sense to fold the documentation site into the main site? Both seem to use the same technology; is it only a historical artifact that they are separate (because docs existed before the main site overhaul)?

**Comment by heathermiller** [comment] 2015-11-12 10:57
For years now I've wanted to fold them together in appearance. 

I like that they're kept separate right now due mainly to the heinous amount of time it takes to build the doc-site due to (a) Ruby/Jekyll, and (b) Liquid templating. Back in the day when I put together the doc-site, enabling all kinds of indexes to be generated meant an outrageous number of traversals through a global array of all pages in the site. 

Right now the build times for scala-lang are sane. So if we combine the two into one repo and if we keep using the same site generator (Jekyll), the build times would be untenable for the agglomerate site. If that's clear.

**Comment by soc** [comment] 2015-11-12 11:08
Mhhh sounds bad, but would the index stuff matter during development?

**Comment by heathermiller** [comment] 2015-11-12 11:25
Yes. Building it to see if the edits you made parsed takes tens of minutes.

**Comment by soc** [comment] 2015-11-12 11:26
Argh, that sounds bad. :-(

**Comment by SethTisue** [comment] 2015-11-12 13:27
thinking about this, but in the meantime, @heathermiller can you give seth@tisue.net the power on Disqus to delete bad comments, so if I happen to see one I can just do it?

**Comment by smarter** [comment] 2015-11-12 14:10
FYI, Jekyll 3.0 which was very recently released has experimental incremental builds: https://jekyllrb.com/news/

**Comment by soc** [comment] 2015-11-12 14:36
Thanks @smarter!

> Changed version support: no support for Ruby 1.9.3, added basic JRuby support.

Maybe this could speed things up a bit?

**Comment by heathermiller** [comment] 2015-11-12 14:40
Perhaps. The problem is more the templating engine + how Jekyll fundamentally works that's stupid. For every language flag, index, anything, the Jekyll has to iterate through every page on the site because there's a global array of pages and no possibility of making new arrays with subsets of pages. If that's clear. So you spend minutes on the same traversal thousands of times.

This was all back in the day, of course.

**Comment by heathermiller** [comment] 2015-11-12 14:42
I just deleted most of the offensive comments in the past several months (there were only 4-5), and I strengthened the word filter a little bit. So, hopefully less cursing gets through now.

@SethTisue – you have admin rights for Disqus. Emailing you more info now.

**Comment by heathermiller** [comment] 2015-11-13 13:45
Closing, as spammy comments have been removed, and word filter to catch profanity updated to protect against future abusive language.

For other tangential issues, please open a new issue

**Closed by heathermiller** 2015-11-13 13:45 UTC

**Comment by SethTisue** [comment] 2015-11-13 16:17
I withdraw my suggestion to disable Disqus.
